In [4]:
import pandas as pd
reviews = pd.read_json('data/reviews.json')
reviews

,number,author,title,url,text
0,100,by Nora Ephron (2006),I Feel Bad About My Neck,https://www.theguardian.com/film/when-harry-me...,When Harry Met Sally | Film | The Guardian\nSk...
1,99,"by Alain Mabanckou (2005), translated by Helen...",Broken Glass,https://www.theguardian.com/books/2009/feb/21/...,Duck soup | Fiction | The Guardian\nSkip to ma...
2,98,"by Stieg Larsson (2005), translated by Steven ...",The Girl,https://www.theguardian.com/books/2008/jan/06/...,Let's play corpse and robbers | Books | The Gu...
3,97,by JK Rowling (2000),Harry Potter and the Goblet of Fire,https://www.theguardian.com/books/2007/jul/29/...,Has Rowling got another trick up her sleeve? |...
4,96,by Hanya Yanagihara (2015),A Little Life,https://www.theguardian.com/books/2015/aug/05/...,A Little Life by Hanya Yanagihara review – unu...
...,...,...,...,...,...
79,6,by Philip Pullman (2000),The Amber Spyglass,https://www.theguardian.com/books/2000/oct/28/...,Rational magic | Children and teenagers | The ...
80,5,"by WG Sebald (2001), translated by Anthea Bell...",Austerlitz,https://www.theguardian.com/books/2001/sep/29/...,Long and winding river | Books | The Guardian\...
81,4,by Kazuo Ishiguro (2005),Never Let Me Go,https://www.theguardian.com/books/2005/feb/26/...,Clone alone | Books | The Guardian\nSkip to ma...
82,2,by Marilynne Robinson (2004),Gilead,https://www.theguardian.com/books/2005/apr/16/...,Gilead by Marilynne Robinson review – the dama...
83,1,by Hilary Mantel (2009),Wolf Hall,https://www.theguardian.com/books/2009/may/02/...,Wolf Hall by Hilary Mantel – review | Hilary M...

In [5]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   number  84 non-null     int64
 1   author  84 non-null     object
 2   title   84 non-null     object
 3   url     84 non-null     object
 4   text    84 non-null     object
dtypes: int64(1), object(4)
memory usage: 3.4+ KB

In [6]:
import pandas as pd
mwords = pd.read_csv('data/moodywoords.csv')
mwords

,Book Id,admiration,adoration,aesthetic appreciation,amusement,anger,anxiety,awe,awkwardness,boredom,...,horror,interest,joy,nostalgia,relief,romance,sadness,satisfaction,sexual desire,surprise
0,11111,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
import WordCounter as wc
inst = wc.WordCounter()

AttributeError: 'WordCounter' object has no attribute 'countWords'